AUX_FILES = \
    *.aux *.bbl *.blg *.brf *.idx *.ilg *.ind *.lof *.log \
    *.lot *.out *.toc *.acn *.acr *.alg *.glg *.glo *.gls \
    *.fls *.fdb_latexmk *.synctex.gz *.nav *.snm *.vrb *.xdv

# Default target: clean
clean:
	rm -f $(AUX_FILES)